@startuml Class_Diagram
skinparam linetype ortho

class Administrator {
    +int id
    +string username
    +string password
    +string nama_lengkap
    +login()
    +logout()
}

class Pendaftar {
    +int id
    +string no_pendaftaran
    +string kode_akses
    +string nisn
    +string nama_lengkap
    +string jenis_kelamin
    +date tanggal_lahir
    +string status_pendaftaran
    +float nilai_rata_rata
    +string status_kelulusan
    +daftarAwal()
    +lengkapiBiodata()
    +cekStatus()
}

class OrangTua {
    +int id
    +int pendaftar_id
    +string nama_ayah
    +string pekerjaan_ayah
    +string nama_ibu
    +string pekerjaan_ibu
    +string no_telp
}

class SekolahAsal {
    +int id
    +int pendaftar_id
    +string npsn
    +string nama_sekolah
    +string alamat_sekolah
}

class Dokumen {
    +int id
    +int pendaftar_id
    +string jenis_dokumen
    +string file_path
    +string status_verifikasi
    +string catatan_admin
    +upload()
}

class Pengaturan {
    +int id
    +int kuota_penerimaan
    +date tanggal_buka
    +date tanggal_tutup
}

Pendaftar "1" *-- "1" OrangTua : memiliki >
Pendaftar "1" *-- "1" SekolahAsal : dari >
Pendaftar "1" *-- "0..*" Dokumen : mengunggah >
Administrator "1" ..> "0..*" Pendaftar : memverifikasi >
@enduml
